# WhatsApp Bot with Ollama Integration

services:
  whatsapp-bot:
    build: .
    container_name: whatsapp-bot
    network_mode: host  # Allows accessing localhost services on host
    restart: unless-stopped
    extra_hosts:
      - "homeassistant.local:192.168.1.100"  # Reemplaza con la IP real de tu Home Assistant
    env_file:
      - .env
    volumes:
      - ./session:/app/session
    # Uncomment for debugging
    # ports:
    #   - "3000:3000"
